[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}'

[variables]
PYTHON_VERSION = '3.11'